-- Adds a stable, DB-native URL identifier to coin_type_hierarchy, mirroring
-- mints.mint_code exactly: /coin-types/[slug] currently recomputes a slug at
-- request time (lib/coin-type-catalog.ts buildCoinTypeNodes -> slugify() +
-- uniqueSlug()), which means resolving slug -> row requires fetching every
-- coin_type_hierarchy row and rebuilding the whole ~72-row tree in memory
-- just to find one. type_code makes that a direct .eq('type_code', ...)
-- lookup instead, same pattern getMintByCode/getSite already use.
--
-- Only rows that terminate a browsable node get a code -- which, checked
-- live, is every row in this table: coin_type_hierarchy_path_unique already
-- means each row is some node's own row, and the only two labels that are
-- pure grouping buckets with no row of their own are the two level1 roots
-- (钱币/Coin, 钱范/Coin Mould) -- which per
-- components/coin-types/CoinTypeDetailContent.tsx's parent-link logic
-- ("Level 1 ... has no page of its own to link to") were never a browsable
-- page anyway. So every current /coin-types/[slug] page maps 1:1 to a row
-- here.
--
-- Values below were generated by actually running the live
-- buildCoinTypeNodes() against the current 72 rows (not hand-derived), so
-- every type_code exactly matches that row's slug as computed by the app
-- today -- existing /coin-types/[slug] URLs keep working unchanged once the
-- read path is switched over to this column.
--
-- Run by hand in the Supabase SQL editor -- this repo has no migration
-- runner, scripts/*.sql is the existing convention (see add-flat-views.sql).
-- Idempotent: safe to re-run.

alter table public.coin_type_hierarchy
  add column if not exists type_code text;

update public.coin_type_hierarchy as h
set type_code = v.type_code
from (values
  ('cebabd41-e87d-4518-b994-372ab58971d1', 'spade-coin'),
  ('92a20fb2-0017-4acd-8134-5a9adab38b24', 'hollow-socket-spade'),
  ('9b419f9d-511a-49a4-94d7-ea6b74c070df', 'flat-shoulder-hollow-socket-spade'),
  ('1c634a08-ba3c-4984-b46f-d404da3e15a1', 'large-flat-shoulder-hollow-socket-spade'),
  ('d23bb231-85b3-4a09-9792-d2f4247aad87', 'small-flat-shoulder-hollow-socket-spade'),
  ('d592240d-5bd3-493d-9736-9351501464d6', 'pointed-shoulder-hollow-socket-spade'),
  ('b0a50498-0697-4da0-b7b3-41d78ec246b9', 'slanted-shoulder-hollow-socket-spade'),
  ('992d17d8-8656-47ee-a1a6-c450fc93ca2d', 'flat-handle-spade'),
  ('17484bd0-b8d0-42b4-acfb-3cd6b9ffdbe4', 'square-foot-spade'),
  ('d8efa5e5-5bea-4467-91cb-6dc0d99fed8a', 'large-square-foot-spade'),
  ('6fcc94d5-69ca-443e-a687-c25b28ed4695', 'pointed-foot-spade'),
  ('a5c0808a-f00e-44ed-9098-9fe394813edf', 'large-pointed-foot-spade'),
  ('10bf70c8-ec88-4d3c-8ec6-0414d2a12ca6', 'quasi-square-foot-spade'),
  ('f790da75-676a-4e63-a236-f4611e004cef', 'quasi-round-foot-spade'),
  ('74e2c882-97f8-4f69-8579-b0850edf8822', 'linked-spade'),
  ('90a8eacb-cd58-44be-af4e-0d5d1887d8ae', 'bridge-foot-spade'),
  ('efe61154-76b0-4b71-bbb1-4a22f3ade668', 'sharp-cornered-spade'),
  ('593407a4-f144-4330-b114-f21c82344aca', 'large-sharp-cornered-spade'),
  ('3570f578-b511-44e3-8aee-d31d3a5c0b88', 'three-hole-spade'),
  ('2abe3130-b336-428f-a7ec-641eb8885cbe', 'flat-shoulder-solid-head-spade'),
  ('88328020-5c5f-4c93-a67a-341808e123b1', 'swallow-tailed-spade'),
  ('1edb1c0f-cc14-4296-ac0c-d7d6b1c9d272', 'round-foot-spade'),
  ('4db7a953-0dc1-4f10-a427-c367c8ac645d', 'large-round-foot-spade'),
  ('19977bb7-be0d-45e1-b128-15b59f5dd35d', 'knife-shaped-coin'),
  ('50753dcb-bf17-4d49-bd50-033589d3b3fd', 'pointed-tip-knife'),
  ('ea142fec-4d2d-43de-9461-9c7e534710ff', 'ming-knife'),
  ('c7e2ef28-9a6a-4182-ab2b-95e91eee23ec', 'curved-back-ming-knife'),
  ('fc6c2585-4c3e-48c2-8694-fc343f8530ca', 'angled-back-ming-knife'),
  ('9561ba74-e63a-44db-8916-b570d0b58187', 'qi-large-knife'),
  ('f06070b5-ea4c-4ed8-aaba-97d2367377e2', 'qi-ming-knife'),
  ('35872b03-a0f0-4b10-9102-7ad01420154d', 'primitive-large-knife'),
  ('9e9b81ff-711e-413e-810a-6e60797d3a93', 'needle-tip-knife'),
  ('2fb1a139-e332-4b15-9b39-6b3686dc61d7', 'straight-back-knife'),
  ('fef5cfd1-2787-4285-8dcb-380313bd723c', 'round-coin'),
  ('a3561514-c0a1-4972-bc52-4dc096d7ca47', 'gold-plate'),
  ('2b11e4c6-969a-40e8-a303-3a3b303b5dfa', 'gold-cake'),
  ('8dc91245-750c-40e0-886e-beae31a359f6', 'horse-hoof-gold'),
  ('af532671-5026-475f-9204-11b1ec58d84e', 'monetary-plaque'),
  ('37d4cbd2-31e6-441e-a128-11b525037dce', 'ant-nose-coin'),
  ('bda7f44e-e6e9-4716-be8d-cae33548bbc7', 'spade-coin-mould'),
  ('9f7abc6b-5c3e-4e6d-9cd9-0a44a809ea63', 'hollow-socket-spade-mould'),
  ('62b7f14f-3f99-4742-80e2-59b4146b309b', 'flat-shoulder-hollow-socket-spade-mould'),
  ('ac68370a-e423-440e-ab8c-be96d219f36b', 'large-flat-shoulder-hollow-socket-spade-mould'),
  ('b26cdf6c-9a6c-41b3-af70-22a3785d5207', 'small-flat-shoulder-hollow-socket-spade-mould'),
  ('7340a216-9d0c-4634-a7b5-3647f606f39f', 'pointed-shoulder-hollow-socket-spade-mould'),
  ('ee861229-1a03-4d9a-812d-e53ef95a9317', 'slanted-shoulder-hollow-socket-spade-mould'),
  ('ab56b106-b14f-4e58-976a-e105813cf799', 'flat-handle-spade-mould'),
  ('9f53cb82-8e19-41a4-b15a-984067fe53b2', 'square-foot-spade-mould'),
  ('77b675d8-55ab-45ae-aae5-79d30564c034', 'large-square-foot-spade-mould'),
  ('f7c140b8-683e-412c-9c87-28e7cfe2e9cf', 'pointed-foot-spade-mould'),
  ('3c85bdd7-0047-47aa-92b6-f34cbf9ef378', 'large-pointed-foot-spade-mould'),
  ('4d320c04-c92e-4432-9bba-4e3ecf6bd850', 'linked-spade-mould'),
  ('efc39905-94c9-4a7d-87c0-27e361130439', 'bridge-foot-spade-mould'),
  ('04ecd6ae-fda5-4dae-807e-69d1669505bb', 'sharp-cornered-spade-mould'),
  ('851b7c7a-8cc6-4b78-ad71-6b8fd8cb830e', 'large-sharp-cornered-spade-mould'),
  ('d7826ded-2014-4a4d-8db5-f7e06a7a0cb6', 'three-hole-spade-mould'),
  ('f5af38a6-c84d-47d2-b016-20e3c0bc15b2', 'flat-shoulder-solid-head-spade-mould'),
  ('5c499357-0644-4615-b62e-56d5700e1476', 'swallow-tailed-spade-mould'),
  ('17928cdd-f17a-4cc9-b1f4-48d03c5a1782', 'round-foot-spade-mould'),
  ('d7022f25-f420-4981-ab2c-ff668f2916fd', 'large-round-foot-spade-mould'),
  ('09772bfb-5c8a-4715-b7c3-38a8ceb1f255', 'knife-shaped-coin-mould'),
  ('49d3f142-c1ca-4532-b50e-52394a09ee04', 'pointed-tip-knife-mould'),
  ('531606fe-ae6d-42a8-93f0-f16392970513', 'ming-knife-mould'),
  ('77ba42b7-d242-4181-93a0-eb5516a416d3', 'curved-back-ming-knife-mould'),
  ('edf71ce9-5165-48fc-8324-88be187d0cf0', 'angled-back-ming-knife-mould'),
  ('218beda5-70fa-4b62-976a-cd39cafe2813', 'qi-large-knife-mould'),
  ('1607e4cd-ce7c-401f-85ef-8eda6ccec054', 'qi-ming-knife-mould'),
  ('9ced7bd4-aad0-4e33-b7a1-e5da64f619fa', 'primitive-large-knife-mould'),
  ('5fd1adca-dd46-4df0-8b72-1cb77646fbee', 'needle-tip-knife-mould'),
  ('db354963-63c0-4c2c-9939-589fb4f08e2c', 'straight-back-knife-mould'),
  ('c6de3317-cb5b-43b8-9634-bed49e8e3b68', 'round-coin-mould'),
  ('cc4e0dc1-f0c2-405a-b4d7-cd7cbe071ac1', 'ant-nose-coin-mould')
) as v(id, type_code)
where h.id = v.id::uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'coin_type_hierarchy_type_code_unique'
    and conrelid = 'public.coin_type_hierarchy'::regclass
  ) then
    alter table public.coin_type_hierarchy
    add constraint coin_type_hierarchy_type_code_unique unique (type_code);
  end if;
end $$;

alter table public.coin_type_hierarchy
  alter column type_code set not null;

comment on column public.coin_type_hierarchy.type_code is
  'Stable URL slug for /coin-types/[slug] -- previously computed at runtime via slugify(name_en)/uniqueSlug() in lib/coin-type-catalog.ts buildCoinTypeNodes (the two level1 roots, 钱币/钱范, never get a page and so never need one). Set here on insert going forward by lib/admin/taxonomy-actions.ts createCoinTypeHierarchy, the same way mints.mint_code is generated by lib/admin/mints-actions.ts createMint.';
