#!/usr/bin/env python3
"""
Exports every table in the Supabase Postgres database (except the auth and
storage schemas, and Supabase's own internal schemas) and converts it into a
single MySQL 8 .sql file that recreates the tables, indexes, foreign keys,
CHECK constraints, views and data.

Two phases, so the slow network part only has to happen once:

  1. download -- reads the Postgres DDL for every table/index/constraint/view
     (as Postgres itself prints it) into <out-dir>/download/schema.json, and
     streams every row to <out-dir>/download/<schema>.<table>.jsonl
  2. convert  -- parses that DDL with sqlglot, rewrites the syntax tree for
     MySQL, and writes <out-dir>/mysql_dump.sql (data INSERTs are also
     generated by sqlglot, so quoting/escaping is MySQL's)

Usage:
  conda activate general
  pip install sqlglot "psycopg[binary]"
  DATABASE_URL='postgresql://postgres.<ref>:<password>@<pooler-host>:5432/postgres' \
    python scripts/pg-to-mysql.py
  python scripts/pg-to-mysql.py --skip-download   # re-convert from local files

  mysql -u <user> -p <database> < pg_export/mysql_dump.sql

Use the database password from Supabase -> Project Settings -> Database (the
API keys won't work here); the session-mode pooler URL works over IPv4.

Conversion notes:
  - Tables in `public` keep their names; tables in any other schema become
    `<schema>__<table>`, since a MySQL database has no schemas.
  - uuid -> CHAR(36), timestamptz -> DATETIME(6) in UTC, jsonb/arrays -> JSON,
    boolean -> TINYINT(1), serial/identity -> AUTO_INCREMENT.
  - text -> LONGTEXT, except text columns used in a key/index, which become
    VARCHAR(n) sized to fit InnoDB's 3072-byte index limit (the script fails
    if existing data is longer than that).
  - Collation is utf8mb4_0900_bin so uniqueness and comparisons stay
    case-sensitive, as they are in Postgres.
  - CHECK constraints and views are translated by sqlglot and written at the
    end of the file (after all data), so if MySQL rejects one, every table and
    row is already loaded. Views sqlglot can't translate are hand-written in
    VIEW_OVERRIDES.
  - SCHEMA_ONLY_TABLES (deleted_rows) are created empty; EXCLUDED_TABLES
    (ans_data_upload) and EXCLUDED_COLUMNS (ans_data.upload_id) are left out.
  - Not converted (reported as warnings): triggers, functions, RLS policies,
    expression/non-btree indexes, partial indexes other than
    `WHERE col IS NOT NULL`, column defaults that aren't a
    literal, now(), or a uuid generator, and any CHECK/view that sqlglot
    can't express in MySQL.
"""

import argparse
import datetime as dt
import decimal
import json
import os
import sys
import uuid
import zlib
from pathlib import Path

import sqlglot
from sqlglot import exp
from sqlglot.errors import ErrorLevel, SqlglotError

EXCLUDED_SCHEMAS = [
    # requested
    "auth", "storage",
    # Postgres internals
    "pg_catalog", "information_schema", "pg_toast",
    # Supabase platform internals (no app data)
    "extensions", "graphql", "graphql_public", "realtime", "_realtime",
    "supabase_functions", "supabase_migrations", "vault", "pgsodium",
    "pgsodium_masks", "net", "cron", "pgbouncer", "_analytics",
]

# Tables whose structure is migrated but whose rows are not.
SCHEMA_ONLY_TABLES = ["public.deleted_rows"]

# Tables left out of the export entirely.
EXCLUDED_TABLES = ["public.ans_data_upload"]

# Columns left out of the export, along with any key/index/constraint on them.
EXCLUDED_COLUMNS = {"public.ans_data": ["upload_id"]}

# Views sqlglot can't translate, rewritten for MySQL by hand. Keep these in
# sync with the Postgres definition if it changes.
VIEW_OVERRIDES = {
    # Postgres version uses array_agg(...) FILTER (WHERE ...), jsonb_agg, and
    # (array_agg(... ORDER BY ...))[1]. inscriptions/type_labels become JSON
    # arrays; element order isn't guaranteed (it isn't in Postgres either for
    # type_labels).
    "public.v_mint_stats": """\
SELECT
  m.id AS mint_id,
  m.mint_code,
  COALESCE(fs.find_count, 0) AS find_count,
  COALESCE(fs.coin_count, 0) AS coin_count,
  COALESCE(fs.site_count, 0) AS site_count,
  COALESCE(fi.inscriptions, JSON_ARRAY()) AS inscriptions,
  COALESCE(ic.issue_count, 0) AS issue_count,
  COALESCE(tl.type_labels, JSON_ARRAY()) AS type_labels
FROM mints m
LEFT JOIN (
  SELECT ci.mint_id,
    COUNT(f.id) AS find_count,
    CAST(SUM(COALESCE(f.quantity_total, f.quantity_estimated, f.quantity_min, 0)) AS SIGNED) AS coin_count,
    COUNT(DISTINCT ctx.site_code) AS site_count
  FROM coin_issues ci
  JOIN finds f ON f.coin_issues_id = ci.id
  JOIN contexts ctx ON ctx.context_code = f.context_code
  GROUP BY ci.mint_id
) fs ON fs.mint_id = m.id
LEFT JOIN (
  SELECT d.mint_id, JSON_ARRAYAGG(d.inscription) AS inscriptions
  FROM (
    SELECT DISTINCT ci.mint_id, TRIM(ins.inscription_zh) AS inscription
    FROM coin_issues ci
    JOIN finds f ON f.coin_issues_id = ci.id
    JOIN contexts ctx ON ctx.context_code = f.context_code
    JOIN inscriptions ins ON ins.id = ci.inscription_id
    WHERE TRIM(ins.inscription_zh) <> ''
  ) d
  GROUP BY d.mint_id
) fi ON fi.mint_id = m.id
LEFT JOIN (
  SELECT mint_id, COUNT(*) AS issue_count FROM coin_issues GROUP BY mint_id
) ic ON ic.mint_id = m.id
LEFT JOIN (
  SELECT deduped.mint_id, JSON_ARRAYAGG(JSON_OBJECT('zh', deduped.zh, 'en', deduped.en)) AS type_labels
  FROM (
    SELECT mint_id, zh, en,
      ROW_NUMBER() OVER (PARTITION BY mint_id, zh
                         ORDER BY coin_type_code IS NULL, coin_type_code) AS rn
    FROM (
      SELECT mint_id,
        COALESCE(minor_type_zh, major_type_zh) AS zh,
        CASE WHEN minor_type_zh IS NOT NULL THEN minor_type_en ELSE major_type_en END AS en,
        coin_type_code
      FROM v_coin_issues_flat
    ) labels
    WHERE zh <> ''
  ) deduped
  WHERE deduped.rn = 1
  GROUP BY deduped.mint_id
) tl ON tl.mint_id = m.id""",
}

INDEX_BYTE_LIMIT = 3072
BATCH_ROWS = 500


# ── download ────────────────────────────────────────────────────────────

TABLES_SQL = """
select n.nspname, c.relname, c.oid
from pg_class c join pg_namespace n on n.oid = c.relnamespace
where c.relkind in ('r', 'p') and not c.relispartition
  and n.nspname <> all(%s) and n.nspname not like 'pg\\_%%'
  -- skip tables owned by extensions (e.g. PostGIS's spatial_ref_sys)
  and not exists (select 1 from pg_depend d
                  where d.objid = c.oid and d.deptype = 'e')
order by 1, 2
"""

COLUMNS_SQL = """
select quote_ident(a.attname), format_type(a.atttypid, a.atttypmod),
       a.attnotnull, pg_get_expr(d.adbin, d.adrelid), a.attidentity <> ''
from pg_attribute a
left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
where a.attrelid = %s and a.attnum > 0 and not a.attisdropped
order by a.attnum
"""

CONSTRAINTS_SQL = """
select quote_ident(conname), pg_get_constraintdef(oid)
from pg_constraint
where conrelid = %s and contype in ('p', 'u', 'f', 'c')
order by contype = 'p' desc, conname
"""

# indexes that don't already back a PRIMARY KEY / UNIQUE constraint
INDEXES_SQL = """
select pg_get_indexdef(i.indexrelid)
from pg_index i join pg_class ic on ic.oid = i.indexrelid
where i.indrelid = %s
  and not exists (select 1 from pg_constraint c where c.conindid = i.indexrelid)
order by ic.relname
"""

VIEWS_SQL = """
select n.nspname, c.relname, c.relkind, pg_get_viewdef(c.oid, true)
from pg_class c join pg_namespace n on n.oid = c.relnamespace
where c.relkind in ('v', 'm') and n.nspname <> all(%s) and n.nspname not like 'pg\\_%%'
  and not exists (select 1 from pg_depend d
                  where d.objid = c.oid and d.deptype = 'e')
order by 1, 2
"""


def to_jsonable(v):
    """Turn a psycopg value into something json.dumps can write losslessly."""
    if isinstance(v, dt.datetime):
        if v.tzinfo is not None:
            v = v.astimezone(dt.timezone.utc).replace(tzinfo=None)
        return v.isoformat(sep=" ")
    if isinstance(v, (dt.date, dt.time, uuid.UUID, decimal.Decimal, dt.timedelta)):
        return str(v)
    if isinstance(v, (bytes, memoryview)):
        return bytes(v).hex()
    return str(v)


def download(pg_url, dl_dir):
    import psycopg

    dl_dir.mkdir(parents=True, exist_ok=True)
    meta = {"tables": [], "views": []}
    with psycopg.connect(pg_url) as conn:
        # one read-only snapshot, so all tables are mutually consistent
        conn.read_only = True
        conn.isolation_level = psycopg.IsolationLevel.REPEATABLE_READ
        conn.execute("set timezone = 'UTC'")
        # empty search_path makes Postgres schema-qualify every name it prints
        conn.execute("select pg_catalog.set_config('search_path', '', false)")

        for schema, name, oid in conn.execute(TABLES_SQL, (EXCLUDED_SCHEMAS,)).fetchall():
            if f"{schema}.{name}" in EXCLUDED_TABLES:
                continue
            parts = []
            for col, typ, notnull, default, identity in conn.execute(COLUMNS_SQL, (oid,)):
                parts.append(" ".join(filter(None, [
                    col, typ,
                    "GENERATED BY DEFAULT AS IDENTITY" if identity else None,
                    "NOT NULL" if notnull else None,
                    f"DEFAULT {default}" if default is not None and not identity else None,
                ])))
            for con_name, con_def in conn.execute(CONSTRAINTS_SQL, (oid,)):
                parts.append(f"CONSTRAINT {con_name} {con_def}")
            qualified = conn.execute("select %s::regclass::text", (oid,)).fetchone()[0]
            t = {
                "schema": schema,
                "name": name,
                "ddl": f"CREATE TABLE {qualified} (\n  " + ",\n  ".join(parts) + "\n)",
                "indexes": [r[0] for r in conn.execute(INDEXES_SQL, (oid,))],
            }
            meta["tables"].append(t)

            path = dl_dir / f"{schema}.{name}.jsonl"
            rows = 0
            with conn.cursor(name=f"dump_{oid}") as cur, open(path, "w", encoding="utf-8") as f:
                cur.itersize = 2000
                schema_only = f"{schema}.{name}" in SCHEMA_ONLY_TABLES
                cur.execute(f"select * from {qualified}" + (" limit 0" if schema_only else ""))
                f.write(json.dumps([d.name for d in cur.description], ensure_ascii=False) + "\n")
                for row in cur:
                    f.write(json.dumps(list(row), ensure_ascii=False, default=to_jsonable))
                    f.write("\n")
                    rows += 1
            print(f"  downloaded {schema}.{name}: {rows} rows", file=sys.stderr)

        for schema, name, relkind, body in conn.execute(VIEWS_SQL, (EXCLUDED_SCHEMAS,)):
            meta["views"].append({"schema": schema, "name": name,
                                  "materialized": relkind == "m", "select": body})

    (dl_dir / "schema.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False))


# ── convert ─────────────────────────────────────────────────────────────

T = exp.DataType.Type


def mysql_table_name(schema, name):
    return name if schema == "public" else f"{schema}__{name}"


def short_name(name):
    """MySQL identifiers max out at 64 chars."""
    return name if len(name) <= 64 else name[:55] + "_" + format(zlib.crc32(name.encode()), "08x")


def rename_tables(node, alias_renamed=False):
    """Drop schema qualifiers, folding the schema into the table name."""
    for t in list(node.find_all(exp.Table)):
        if not t.args.get("db"):
            continue
        orig = t.name
        new = mysql_table_name(t.args["db"].name, orig)
        t.set("db", None)
        t.set("catalog", None)
        t.set("this", exp.to_identifier(new))
        if alias_renamed and new != orig and not t.alias:
            t.set("alias", exp.TableAlias(this=exp.to_identifier(orig)))
    return node


def mysql_type(dtype):
    """Postgres sqlglot DataType -> (MySQL DataType, value kind, is_text)."""
    build = lambda s: exp.DataType.build(s, dialect="mysql")
    t = dtype.this
    params = [int(p.name) for p in dtype.expressions if p.name.isdigit()]
    if t in (T.ARRAY, T.JSON, T.JSONB) or dtype.args.get("nested"):
        return build("JSON"), "json", False
    if t == T.UUID:
        return build("CHAR(36)"), "str", False
    if t in (T.SMALLINT, T.INT, T.BIGINT, T.FLOAT, T.DOUBLE):
        return dtype, "num", False
    if t == T.BOOLEAN:
        return build("TINYINT(1)"), "bool", False
    if t == T.DECIMAL:
        if len(params) == 2 and params[0] <= 65 and params[1] <= 30:
            return dtype, "num", False
        return build("DECIMAL(65,30)"), "num", False
    if t in (T.TIMESTAMP, T.TIMESTAMPTZ):
        return build("DATETIME(6)"), "str", False
    if t == T.DATE:
        return dtype, "str", False
    if t in (T.TIME, T.TIMETZ):
        return build("TIME(6)"), "str", False
    if t in (T.VARBINARY, T.BINARY):
        return build("LONGBLOB"), "hex", False
    if t == T.VARCHAR and params and params[0] <= 16383:
        return dtype, "str", False
    if t == T.CHAR and params and params[0] <= 255:
        return dtype, "str", False
    if t in (T.TEXT, T.VARCHAR, T.CHAR):
        return build("LONGTEXT"), "str", True
    return None, "other", True  # enums, intervals, geometry, ... -> LONGTEXT


AUTO_INCREMENT = object()


def mysql_default(d, mtype):
    """Postgres default expression -> MySQL default expression, AUTO_INCREMENT,
    or None if it can't be expressed."""
    if isinstance(d, exp.Anonymous) and d.name.lower() == "nextval":
        return AUTO_INCREMENT
    if isinstance(d, (exp.CurrentTimestamp, exp.CurrentTimestampLTZ)) or (
            isinstance(d, exp.Anonymous) and d.name.lower() in
            ("now", "transaction_timestamp", "statement_timestamp", "clock_timestamp")):
        if mtype.this == T.DATETIME:
            return exp.CurrentTimestamp(this=exp.Literal.number(6))
        return None
    if isinstance(d, exp.Uuid) or "uuid_generate_v4" in d.sql().lower():
        return exp.Paren(this=exp.Uuid())
    while isinstance(d, (exp.Cast, exp.Paren)):
        d = d.this
    if isinstance(d, exp.Boolean):
        return exp.Literal.number(1 if d.this else 0)
    if isinstance(d, exp.Neg) and isinstance(d.this, exp.Literal):
        return d
    if isinstance(d, exp.Literal):
        # MySQL only allows literal defaults on TEXT/BLOB/JSON as expressions
        if d.is_string and mtype.this in (T.LONGTEXT, T.JSON, T.LONGBLOB):
            return exp.Paren(this=d)
        return d
    return None


def any_array_to_in(node):
    """`x = ANY (ARRAY['a', 'b'])` (Postgres's spelling of IN) -> `x IN ('a', 'b')`;
    also drops casts on string literals (`'a'::text`), which MySQL can't use."""
    if isinstance(node, exp.EQ) and isinstance(node.expression, exp.Any):
        arr = node.expression.this.unnest()
        if isinstance(arr, exp.Array):
            return exp.In(this=node.this,
                          expressions=[e.transform(any_array_to_in) for e in arr.expressions])
    if isinstance(node, exp.Cast) and isinstance(node.this, exp.Literal) and node.this.is_string:
        return node.this
    return node


def only_not_null_checks(where, cols):
    """True if a partial index's WHERE is just `col IS NOT NULL` (ANDed) on its
    own columns -- MySQL indexes already let any number of NULLs through a
    UNIQUE, so the index means the same thing without the WHERE."""
    if where is None:
        return False
    names = {c.name for c in cols}
    cond = where.this.unnest()
    conds = [c.unnest() for c in (cond.flatten() if isinstance(cond, exp.And) else [cond])]
    return all(
        isinstance(c, exp.Is) and c.args.get("negate")
        and isinstance(c.expression, exp.Null) and c.this.name in names
        for c in conds
    )


def key_column_sets(create, indexes):
    keys = []
    for pk in create.find_all(exp.PrimaryKey):
        keys.append([e.name for e in pk.expressions])
    for u in create.find_all(exp.UniqueColumnConstraint):
        keys.append([e.name for e in u.this.expressions])
    for fk in create.find_all(exp.ForeignKey):
        keys.append([e.name for e in fk.expressions])
    for ix in indexes:
        keys.append([c.name for c in ix.this.args["params"].args["columns"]])
    return keys


def read_rows(path):
    with open(path, encoding="utf-8") as f:
        header = json.loads(f.readline())
        return header, [json.loads(line) for line in f]


def gen(node, **kw):
    return node.sql(dialect="mysql", identify=True, **kw)


def sql_value(v, kind):
    if v is None:
        return exp.Null()
    if kind == "bool":
        return exp.Literal.number(1 if v else 0)
    if kind == "num" and not isinstance(v, str):
        return exp.Literal.number(v)
    if kind == "hex":
        return exp.HexString(this=v)
    if not isinstance(v, str):  # json/arrays, or unmapped types
        v = json.dumps(v, ensure_ascii=False)
    return exp.Literal.string(v)


def convert(dl_dir, out_path):
    meta = json.loads((dl_dir / "schema.json").read_text())
    warnings = []
    warn = warnings.append
    out = open(out_path, "w", encoding="utf-8")
    w = out.write
    w("-- Generated by scripts/pg-to-mysql.py\n")
    w("SET NAMES utf8mb4;\nSET time_zone = '+00:00';\nSET FOREIGN_KEY_CHECKS = 0;\n")
    w("SET UNIQUE_CHECKS = 0;\nSET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO,STRICT_ALL_TABLES';\n\n")

    checks = []  # (table, Constraint) -- added after all data is loaded
    total_rows = 0
    tables = [t for t in meta["tables"] if f"{t['schema']}.{t['name']}" not in EXCLUDED_TABLES]
    for t in tables:
        label = f"{t['schema']}.{t['name']}"
        mname = mysql_table_name(t["schema"], t["name"])
        create = sqlglot.parse_one(t["ddl"], read="postgres")
        header, rows = read_rows(dl_dir / f"{t['schema']}.{t['name']}.jsonl")

        # Excluded columns: drop them from the rows, the column list, and any
        # constraint or index that uses them.
        dropped = set(EXCLUDED_COLUMNS.get(label, []))
        uses_dropped = lambda node: any(
            i.name in dropped for i in node.find_all(exp.Identifier)
            if i is not node.this and not i.find_ancestor(exp.Reference))
        if dropped:
            keep = [i for i, c in enumerate(header) if c not in dropped]
            header = [header[i] for i in keep]
            rows = [[r[i] for i in keep] for r in rows]
            create.this.set("expressions", [
                e for e in create.this.expressions
                if not (isinstance(e, exp.ColumnDef) and e.name in dropped)
                and not (isinstance(e, exp.Constraint) and uses_dropped(e))])

        # Indexes: plain btree column indexes only.
        indexes = []
        for ddl in t["indexes"]:
            ix = sqlglot.parse_one(ddl, read="postgres")
            if dropped and uses_dropped(ix.this.args["params"]):
                continue
            params = ix.this.args["params"]
            using = params.args.get("using")
            cols = [c.this if isinstance(c, exp.Ordered) else c for c in params.args["columns"]]
            if only_not_null_checks(params.args.get("where"), cols):
                params.set("where", None)
            if params.args.get("where") or (using and using.name.lower() != "btree") \
                    or not all(isinstance(c, exp.Column) for c in cols):
                warn(f"{label}: index not converted: {ddl}")
                continue
            params.set("using", None)
            params.set("columns", cols)
            ix.this.set("this", exp.to_identifier(short_name(ix.this.name)))
            indexes.append(rename_tables(ix))

        # Table-level constraints: CHECKs are moved to the end, names shortened,
        # FKs to excluded schemas dropped.
        schema_node = create.this
        kept = []
        for e in schema_node.expressions:
            if isinstance(e, exp.Constraint):
                fk = e.find(exp.ForeignKey)
                if fk:
                    ref = fk.args["reference"].find(exp.Table)
                    if ref.args["db"].name in EXCLUDED_SCHEMAS:
                        warn(f"{label}: foreign key {e.name} -> {ref.args['db'].name}.{ref.name} "
                             f"dropped (referenced schema is excluded)")
                        continue
                cname = e.name if t["schema"] == "public" else f"{t['schema']}__{e.name}"
                e.set("this", exp.to_identifier(short_name(cname)))
                if e.find(exp.CheckColumnConstraint):
                    checks.append((mname, e))
                    continue
            kept.append(e)
        schema_node.set("expressions", kept)
        rename_tables(create)

        # Column types and defaults.
        coldefs = {cd.name: cd for cd in schema_node.expressions if isinstance(cd, exp.ColumnDef)}
        kinds, text_cols = {}, set()
        for name, cd in coldefs.items():
            mtype, kinds[name], is_text = mysql_type(cd.args["kind"])
            if mtype is None:
                warn(f"{label}.{name}: type {cd.args['kind'].sql('postgres')} stored as LONGTEXT")
                mtype = exp.DataType.build("LONGTEXT", dialect="mysql")
            if is_text:
                text_cols.add(name)
            cd.set("kind", mtype)
            constraints = []
            for cc in cd.constraints:
                kind = cc.args["kind"]
                if isinstance(kind, exp.GeneratedAsIdentityColumnConstraint):
                    constraints.append(exp.ColumnConstraint(kind=exp.AutoIncrementColumnConstraint()))
                elif isinstance(kind, exp.DefaultColumnConstraint):
                    d = mysql_default(kind.this, mtype)
                    if d is AUTO_INCREMENT:
                        constraints.append(exp.ColumnConstraint(kind=exp.AutoIncrementColumnConstraint()))
                    elif d is None:
                        warn(f"{label}.{name}: dropped default {kind.this.sql('postgres')}")
                    else:
                        constraints.append(exp.ColumnConstraint(kind=exp.DefaultColumnConstraint(this=d)))
                else:
                    constraints.append(cc)
            cd.set("constraints", constraints)

        # Text columns used in a key must be VARCHAR, and every index must fit
        # in 3072 bytes (4 bytes/char for utf8mb4).
        varchar = {}
        for key in key_column_sets(create, indexes):
            key_text = [n for n in key if n in text_cols]
            if not key_text:
                continue
            other = sum(144 if coldefs[n].args["kind"].sql("mysql") == "CHAR(36)" else 16
                        for n in key if n not in key_text)
            per_col = (INDEX_BYTE_LIMIT - other) // 4 // len(key_text)
            for n in key_text:
                varchar[n] = min(varchar.get(n, per_col), per_col)
        for name, size in varchar.items():
            pos = header.index(name)
            longest = max((len(r[pos]) for r in rows if r[pos] is not None), default=0)
            if longest > size:
                sys.exit(f"error: {label}.{name} is indexed but has a {longest}-char value; "
                         f"MySQL can only index {size} chars here")
            coldefs[name].set("kind", exp.DataType.build(f"VARCHAR({size})", dialect="mysql"))

        create.set("properties", exp.Properties(expressions=[
            exp.EngineProperty(this=exp.var("InnoDB")),
            exp.CharacterSetProperty(this=exp.var("utf8mb4"), default=True),
            exp.CollateProperty(this=exp.var("utf8mb4_0900_bin")),
        ]))
        w(f"DROP TABLE IF EXISTS `{mname}`;\n")
        w(gen(create, pretty=True) + ";\n")
        for ix in indexes:
            w(gen(ix) + ";\n")
        w("\n")

        table = exp.to_table(mname)
        col_kinds = [kinds[c] for c in header]
        for start in range(0, len(rows), BATCH_ROWS):
            values = exp.values([
                tuple(sql_value(v, k) for v, k in zip(row, col_kinds))
                for row in rows[start:start + BATCH_ROWS]
            ])
            w(gen(exp.insert(values, table, columns=header)) + ";\n")
        if rows:
            w("\n")
        total_rows += len(rows)
        print(f"  converted {label}: {len(rows)} rows", file=sys.stderr)

    w("SET FOREIGN_KEY_CHECKS = 1;\nSET UNIQUE_CHECKS = 1;\n\n")

    if checks:
        w("-- CHECK constraints (translated by sqlglot)\n")
    for mname, con in checks:
        con = con.transform(any_array_to_in)
        try:
            w(f"ALTER TABLE `{mname}` ADD {gen(con, unsupported_level=ErrorLevel.RAISE)};\n")
        except SqlglotError as e:
            warn(f"{mname}: CHECK constraint {con.name} not converted ({e})")

    # Views, ordered so each view comes after the views it selects from.
    views = {}
    for v in meta["views"]:
        label = f"{v['schema']}.{v['name']}"
        if v["materialized"]:
            warn(f"{label}: materialized view converted to a plain view")
        try:
            select = sqlglot.parse_one(v["select"], read="postgres")
        except SqlglotError as e:
            warn(f"{label}: view not converted ({e})")
            continue
        deps = {(t.args["db"].name, t.name) for t in select.find_all(exp.Table) if t.args.get("db")}
        select = rename_tables(select.transform(any_array_to_in), alias_renamed=True)
        views[(v["schema"], v["name"])] = (deps, select)
    if views:
        w("\n-- Views (translated by sqlglot)\n")
    done = set()
    while len(done) < len(views):
        ready = [k for k, (deps, _) in views.items()
                 if k not in done and not (deps & views.keys()) - done]
        if not ready:
            warn(f"views not converted (circular dependency): {sorted(views.keys() - done)}")
            break
        for key in ready:
            done.add(key)
            name = mysql_table_name(*key)
            try:
                body = VIEW_OVERRIDES.get(f"{key[0]}.{key[1]}") or \
                    gen(views[key][1], pretty=True, unsupported_level=ErrorLevel.RAISE)
            except SqlglotError as e:
                warn(f"{key[0]}.{key[1]}: view not converted ({e})")
                continue
            w(f"CREATE OR REPLACE VIEW `{name}` AS\n{body};\n\n")

    out.close()
    print(f"wrote {out_path}: {len(tables)} tables, {total_rows} rows", file=sys.stderr)
    if warnings:
        print(f"\n{len(warnings)} warning(s):", file=sys.stderr)
        for msg in warnings:
            print(f"  - {msg}", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pg-url", default=os.environ.get("DATABASE_URL"),
                    help="Postgres connection URL (default: $DATABASE_URL)")
    ap.add_argument("--out-dir", default="pg_export", type=Path)
    ap.add_argument("--skip-download", action="store_true",
                    help="convert the files already in <out-dir>/download")
    args = ap.parse_args()

    dl_dir = args.out_dir / "download"
    if not args.skip_download:
        if not args.pg_url:
            ap.error("set DATABASE_URL or pass --pg-url")
        download(args.pg_url, dl_dir)
    convert(dl_dir, args.out_dir / "mysql_dump.sql")


if __name__ == "__main__":
    main()
